name: terraformtest
on: 
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  check:
    name: tfexec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform'
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setupTerraform
      uses: hashicorp/setup-terraform@v3
#    - name: validate
#      run: |
#        terraform validate
#        code=$(terraform validate -json)
#        hoge=$(echo $code|jq .error_count)
#        echo ${code}
#        echo ${hoge}        
#        if [ $hoge -gt 1 ]; then exit 1; fi;

    - name: terraform fmt
      id: terraformfmt
      run: |
        terraform fmt
        kondo=$(cat com.txt)
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "KONDO<<$EOF"
          echo "$kondo"
          echo "$EOF"
        } >> $GITHUB_ENV
    - name: Create comment file
      run: |
          cat  << EOF > comment.md
          ***Test Failed***
          <details><summary>サマリー</summary>          
          <pre><code class="language-diff">
          ${{env.KONDO}}
          </code></pre>
          </details>
          EOF
    - name: CreatePRcomment
      run: |
        gh pr comment ${{ github.event.number }} --body-file comment.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
