name: terraformtest
on: 
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  check:
    name: tfexec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform'
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setupTerraform
      uses: hashicorp/setup-terraform@v3
    - name: terraform fmt
      run: |
        terraform fmt
    - name: Create comment file
      run: |
          cat  << EOF > comment.md
          ## Test Failed
          <details><summary>サマリー</summary>
          The tests failed. Please check the logs for more information.
          EOF
    - name: CreatePRcomment
      run: |
        gh pr comment ${{ github.event.number }} --body-file comment.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
