name: Dump
on: push
jobs:
  check:
    name: scan
    runs-on: ubuntu-latest
    steps:
    - name: ls
      uses: actions/checkout@v4
    - name: ls
      run: |
        pwd
        ls -l
    - name: tf-scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'config'
        scan-ref:  './terraform'
        