name: terraformtest
on: 
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  check:
    name: tfexec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform'
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setupTerraform
      uses: hashicorp/setup-terraform@v3
    - name: terraform fmt
      id: terraformfmt
      run: |
        terraform fmt
        kondo=$(cat main.tf)
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "KONDO<<$EOF"
          echo "$kondo"
          echo "$EOF"
        } >> $GITHUB_ENV
    - name: Create comment file
      run: |
          cat  << EOF > comment.md
          ## Test Failed
          <details><summary>サマリー</summary>          
          ${{env.KONDO}}
          EOF
          sed -e 's/#/\#/g' comment.md
    - name: CreatePRcomment
      run: |
        gh pr comment ${{ github.event.number }} --body-file comment.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
