name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - run: echo "result2=Hello2" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{steps.source.outputs.result2}}
        run: echo "${RESULT}"