name: terraformtest
on: 
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  check:
    name: tfexec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform'
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setupTerraform
      uses: hashicorp/setup-terraform@v3
    - name: terraform fmt
      id: terraformfmt
      run: |
        terraform fmt
        kondo=$(ls -l)
        echo "KONDO<<EOF" >> $GITHUB_OUTPUT
        echo "$kondo" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Create comment file
      run: |
          cat  << EOF > comment.md
          ## Test Failed
          <summary>サマリー</summary>          
          ```bash
          ${{ steps.terraformfmt.outputs.kondo }}
          ```
          EOF
    - name: CreatePRcomment
      run: |
        gh pr comment ${{ github.event.number }} --body-file comment.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
