name: Dump
on: push
jobs:
  check:
    name: scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform'
    steps:
    - name: ls
      uses: actions/checkout@v4
    - name: ls
      run: |
        pwd
        ls -l
    - name: tf-scan
      uses: aquasecurity/trivy-action@0.28.0
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
      with:
        scan-type: 'config'
        scan-ref:  './terraform'
        format: table
        exit-code: 0
#        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        trivy-config: './trivy.yaml'
#        output: trivy-scan-result.txt
