name: Dump
on: push
jobs:
  check:
    name: scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform'
    steps:
    - name: ls
      uses: actions/checkout@v4
    - name: ls
      run: |
        pwd
        ls -l
    - name: tf-scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'config'
        scan-ref:  './terraform'
        format: table
        exit-code: 1
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        output: trivy-scan-result.txt
    - name: comment-scan-result
      run: |
        if [ -s trivy-scan-result.txt ]; then
          # ファイルに内容がある場合
          echo -e "## 脆弱性スキャン結果\n<details><summary>詳細</summary>\n\n\`\`\`\n$(cat trivy-scan-result.txt)\n\`\`\`\n</details>" > formatted-trivy-result.md
        else
          # ファイルが空の場合
          echo -e "## 脆弱性スキャン結果\n脆弱性が検知されませんでした。" > formatted-trivy-result.md
        fi

    - name: Comment PR with Trivy scan results
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        GITHUB_TOKEN: ${{ secrets.github_token }}
        path: formatted-trivy-result.md
