name: Dump
on: push
jobs:
  check:
    name: scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './terraform'
    steps:
    - name: ls
      uses: actions/checkout@v4
    - name: ls
      run: |
        pwd
        ls -l
    - name: tf-scan
      id: tfscan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'config'
        scan-ref:  './terraform'
        format: table
        exit-code: 0
#        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
#        trivy-config: '/trivy.yml'
    - name: checkfailure
      if: steps.tfscan.outcome == 'failure' 
      run: exit 1